import React, { ReactElement } from "react";
import Head from 'next/head'
import Navbar from '../components/navbar/Navbar'
import Hero from '../components/hero/Hero'
import useAnimation from "../animations";


export default function Home():ReactElement {
  const { app } = useAnimation();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main ref={app}>
        <Navbar />
        <Hero />
      </main>
    </>
  )
}
