import React, { ReactElement } from "react";
import Head from 'next/head'
import Navbar from '../components/navbar/Navbar'
import Hero from '../components/hero/Hero'
import Countries from "../components/countries/Countries";
import Portfolio from "../components/portfolio/Portfolio";
import Story from "../components/story/Story";
import Team from "../components/team/Team";
import Market from "../components/market/Market";
import Footer from "../components/footer/Footer";
import Preloader from "../components/preloader/Preloader";



export default function Home():ReactElement {


  return (
    <>
      <Head>
        <title>DRIVE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
            <>
            <Preloader />
            <div className="app">
              <Navbar />
              <Hero />
              <Story />
              <Countries />
              <Team />
              <Portfolio />
              <Market />
              <Footer />
            </div>
            </>
      </main>
    </>
  )
}
